import Head from "next/head";
import dynamic from "next/dynamic";
import Sidebar from "../components/Sidebar";
import useFetch from "../hooks/useFetch";
import MapWrapper from "../components/MapWrapper";
const Map = dynamic(
  async () => import("../components/Map").then((module) => module.default),
  { ssr: false }
);

export default function Home() {
  const { data, loading } = useFetch(
    "https://corona.lmao.ninja/v2/countries?yesterday=false&sort=cases"
  );
  return (
    <>
      <Head>
        <title>Covid Chart 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex">
        <Sidebar countries={data} loadingCountries={loading}></Sidebar>
        <MapWrapper>
          <Map countries={data} loadingCountries={loading}></Map>
        </MapWrapper>
      </div>
    </>
  );
}
